/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dungeoneditor;

import java.awt.BorderLayout;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author nithrilh
 */
public class IHM extends javax.swing.JFrame {

    private gridDisplay GD = new gridDisplay();
    private NewJDialog nouveau = new NewJDialog(this, true);
    
    public IHM() {
        initComponents();
        getContentPane().add(GD);
        setSize(640,680);
    }
   
    private void nouveau(int X, int Y){
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        gridDisplay1 = new dungeoneditor.gridDisplay();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuNew = new javax.swing.JMenuItem();
        jMenuOpen = new javax.swing.JMenuItem();
        jMenuSave = new javax.swing.JMenuItem();
        jMenuQuit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuOutils = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuMur = new javax.swing.JMenuItem();
        jMenuSol = new javax.swing.JMenuItem();
        jMenuPorte = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuBat = new javax.swing.JMenuItem();
        jMenuSlime = new javax.swing.JMenuItem();
        jMenuScorpion = new javax.swing.JMenuItem();
        jMenuGomme = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout gridDisplay1Layout = new javax.swing.GroupLayout(gridDisplay1);
        gridDisplay1.setLayout(gridDisplay1Layout);
        gridDisplay1Layout.setHorizontalGroup(
            gridDisplay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        gridDisplay1Layout.setVerticalGroup(
            gridDisplay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(gridDisplay1);

        jMenuFile.setText("File");

        jMenuNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuNew.setText("New");
        jMenuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNewActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuNew);

        jMenuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuOpen.setText("Open");
        jMenuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOpenActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuOpen);

        jMenuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuSave.setText("Save");
        jMenuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSaveActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuSave);

        jMenuQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuQuit.setText("Quit");
        jMenuQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuQuitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuQuit);

        jMenuBar1.add(jMenuFile);

        jMenuEdit.setText("Edit");
        jMenuBar1.add(jMenuEdit);

        jMenuOutils.setText("Outils");

        jMenu2.setText("Construction");

        jMenuMur.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, 0));
        jMenuMur.setText("Mur");
        jMenuMur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMurActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuMur);

        jMenuSol.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, 0));
        jMenuSol.setText("Sol placeholder");
        jMenuSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSolActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuSol);

        jMenuPorte.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, 0));
        jMenuPorte.setText("Porte");
        jMenuPorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPorteActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuPorte);

        jMenuOutils.add(jMenu2);

        jMenu3.setText("Créatures");

        jMenuBat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, 0));
        jMenuBat.setText("Chauve-souris");
        jMenuBat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBatActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuBat);

        jMenuSlime.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, 0));
        jMenuSlime.setText("Slime");
        jMenuSlime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSlimeActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuSlime);

        jMenuScorpion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        jMenuScorpion.setText("Scorpions");
        jMenuScorpion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuScorpionActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuScorpion);

        jMenuOutils.add(jMenu3);

        jMenuGomme.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, 0));
        jMenuGomme.setText("Gomme");
        jMenuGomme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGommeActionPerformed(evt);
            }
        });
        jMenuOutils.add(jMenuGomme);

        jMenuBar1.add(jMenuOutils);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQuitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuQuitActionPerformed

    private void jMenuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSaveActionPerformed
        try {
            gridDisplay1.sauvegarder();
        } catch (IOException ex) {
            Logger.getLogger(IHM.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(IHM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuSaveActionPerformed

    private void jMenuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNewActionPerformed
        nouveau.setVisible(true);
    }//GEN-LAST:event_jMenuNewActionPerformed

    private void jMenuBatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBatActionPerformed
        gridDisplay1.setOutil("chauve-souris");
    }//GEN-LAST:event_jMenuBatActionPerformed

    private void jMenuSlimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSlimeActionPerformed
        gridDisplay1.setOutil("slime");
    }//GEN-LAST:event_jMenuSlimeActionPerformed

    private void jMenuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOpenActionPerformed
        try {
            gridDisplay1.charger();
        } catch (IOException ex) {
            Logger.getLogger(IHM.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(IHM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuOpenActionPerformed

    private void jMenuGommeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGommeActionPerformed
        gridDisplay1.setOutil("gomme");
    }//GEN-LAST:event_jMenuGommeActionPerformed

    private void jMenuSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSolActionPerformed
        gridDisplay1.setOutil("sol");
    }//GEN-LAST:event_jMenuSolActionPerformed

    private void jMenuMurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMurActionPerformed
        gridDisplay1.setOutil("mur");
    }//GEN-LAST:event_jMenuMurActionPerformed

    private void jMenuPorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPorteActionPerformed
        gridDisplay1.setOutil("porte");
    }//GEN-LAST:event_jMenuPorteActionPerformed

    private void jMenuScorpionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuScorpionActionPerformed
        gridDisplay1.setOutil("scorpion");
    }//GEN-LAST:event_jMenuScorpionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IHM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dungeoneditor.gridDisplay gridDisplay1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuBat;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuGomme;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuMur;
    private javax.swing.JMenuItem jMenuNew;
    private javax.swing.JMenuItem jMenuOpen;
    private javax.swing.JMenu jMenuOutils;
    private javax.swing.JMenuItem jMenuPorte;
    private javax.swing.JMenuItem jMenuQuit;
    private javax.swing.JMenuItem jMenuSave;
    private javax.swing.JMenuItem jMenuScorpion;
    private javax.swing.JMenuItem jMenuSlime;
    private javax.swing.JMenuItem jMenuSol;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
